global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3000']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3001']

  - job_name: 'order-service-fragile'
    static_configs:
      - targets: ['order-service-fragile:3002']
